FROM amancevice/pandas:1.2.4-alpine
RUN apk update && apk add python3-dev gcc libc-dev
RUN python -m pip install --upgrade pip virtualenv poetry
COPY poetry.lock /poetry.lock
COPY pyproject.toml /pyproject.toml
RUN cd / && poetry install
COPY dacot_models /dacot_models
RUN cd / && poetry add /dacot_models/
COPY export-agent /export-agent
COPY run-export-agent.sh /export-agent/run-export-agent.sh
WORKDIR /export-agent
ENTRYPOINT /usr/local/bin/poetry run /bin/sh /export-agent/run-export-agent.sh
